AWSTemplateFormatVersion: '2010-09-09'
Description: HTTP Lambda Bridge demo ECR Repo
Resources:

  DemoRepository:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: http-lambda-bridge-demo
      ImageScanningConfiguration: 
        ScanOnPush: true    

Outputs:
  DemoRepoUri:
    Value: !GetAtt DemoRepository.RepositoryUri