AWSTemplateFormatVersion: '2010-09-09'
Description: HTTP Lambda Bridge demo ECR Repo
Resources:

  HTTPLambdaBridgeDemoRepository:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: http-lambda-bridge-demo
      ImageScanningConfiguration: 
        ScanOnPush: true    

Outputs:
  HTTPLambdaBridgeDemoRepository:
    Value: !GetAtt HTTPLambdaBridgeDemoRepository.RepositoryUri